config/routes.rb
Omniauth::Application.routes.draw do

  resources :users
  resources :authorizations
  resource :session, :only => [:new, :create, :destroy]
  resources :user_sessions
  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
  match '/auth/:provider/callback', :to => 'authorizations#create'
  match '/auth/failure', :to => 'authorizations#failure'
  

  root :to => "users#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password_confirmation
  has_many :authorizations, :dependent => :destroy
  
  acts_as_authentic do |c|
    c.ignore_blank_passwords = true #ignoring passwords
    c.validate_password_field = false #ignoring validations for password fields
  end
  
  #here we add required validations for a new record and pre-existing record
  validate do |user|
    if user.new_record? #adds validation if it is a new record
      user.errors.add(:password, "is required") if user.password.blank? 
      user.errors.add(:password_confirmation, "is required") if user.password_confirmation.blank?
      user.errors.add(:password, "Password and confirmation must match") if user.password != user.password_confirmation
    elsif !(!user.new_record? && user.password.blank? && user.password_confirmation.blank?) #adds validation only if password or password_confirmation are modified
      user.errors.add(:password, "is required") if user.password.blank?
      user.errors.add(:password_confirmation, "is required") if user.password_confirmation.blank?
      user.errors.add(:password, " and confirmation must match.") if user.password != user.password_confirmation
      user.errors.add(:password, " and confirmation should be atleast 4 characters long.") if user.password.length < 4 || user.password_confirmation.length < 4
    end
  end  
  
  def self.create_from_hash(hash)
    user = User.new(:username => hash['user_info']['name'].downcase)
    user.save(false) #create the user without performing validations. This is because most of the fields are not set.
    user.reset_persistence_token! #set persistence_token else sessions will not be created
    user
  end
  
  
  # def apply_omniauth(omniauth)
  #   self.email = omniauth['user_info']['email'] if email.blank?
  #   authorizations.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created user."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end
  
  def edit
    @user = current_user
    @authorizations = current_user.authorizations if current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated user."
      redirect_to root_url
    else
      render :action => 'edit'
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/users/_form.html.erb
<% form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit %></p>
  
  <%= render :partial => "omniauth_connect" if current_user != nil && current_user.id == @user.id %>
  
<% end %>

app/views/users/_omniauth_connect.erb
<div id="omniauth_connect">
  <% if @authorizations %>
    <% unless @authorizations.empty? %>
      <p><b>You can sign in to this account using:</b></p>
      <div class="authentications">
        <% for authorization in @authorizations %>
          <span class="auth_providers_used">
            <%= image_tag "auth/#{authorization.provider}_32.png" %>
            <%= link_to image_tag("auth/remove.png"), authorization, :confirm => "Are you sure you want to remove #{authorization.provider} authentication option?", :method => :delete, :class => "omniauth_remove", :title => "remove #{authorization.provider} authentication option?" %>
          </span>
        <% end %>
        <div class="clear"></div>
      </div>
    <% end %>
    <p><b>Add another service to sign in with:</b></p>
  <% else %>
    <p><b>Add one of the services to sign in with:</b></p>
  <% end %>
  <a href="/auth/twitter" class="auth_provider" title = "Add twitter service to sign in with">
    <%= image_tag "auth/twitter_64.png", :alt => "Twitter" %>
  </a>
  <a href="/auth/facebook" class="auth_provider" title = "Add facebook to sign in with">
    <%= image_tag "auth/facebook_64.png", :alt => "Facebook" %>
  </a>
  <!-- <a href="/auth/open_id?openid_url=https://www.google.com/accounts/o8/id" class="auth_provider" title = "Add google to sign in with"> -->
    <%#= image_tag "auth/google_32.png", :alt => "Google" %>
  </a>
  <div class="clear"></div>
</div>  

app/views/users/_user_bar.html.erb
<% if logged_in? -%>
  <div id="user-bar-greeting">Logged in as <%= link_to_current_user :content_method => :login %></div>
  <div id="user-bar-action"  >(<%= link_to "Log out", logout_path, { :title => "Log out" }    %>)</div>
<% else -%>
  <div id="user-bar-greeting"><%= link_to_login_with_IP 'Not logged in', :style => 'border: none;' %></div>
  <div id="user-bar-action"  ><%= link_to "Log in",  login_path,  { :title => "Log in" } %> /
                               <%= link_to "Sign up", signup_path, { :title => "Create an account" } %></div>
<% end -%>

app/views/users/edit.html.erb
<% title "Edit Your Profile" %>

<%= render :partial => 'form' %>

app/views/users/index.html.erb
<div id="articles">
  <h2>
    Sample Page
  </h2>
  <div class="created_at">Created on <%= Time.now.strftime('%b %d, %Y') %></div>
  <div class="content"><%= simple_format("This is a sample content for this page. " * 20) %></div>
</div>

app/views/users/new.html.erb
<% title "Sign up" %>

<%= render :partial => 'form' %>

<h1>OR</h1>
<h3>Sign in with</h3>
<%#= link_to image_tag("auth/google_64.png"), "/auth/open_id?openid_url=https://www.google.com/accounts/o8/id" %>
<% ["twitter","facebook"].each do |provider| %>
  <%= link_to image_tag("auth/#{provider}_64.png"), "/auth/#{provider}" %>
<% end %>