config/routes.rb
Omniauth::Application.routes.draw do

  resources :users
  resources :authorizations
  resource :session, :only => [:new, :create, :destroy]
  resources :user_sessions
  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
  match '/auth/:provider/callback', :to => 'authorizations#create'
  match '/auth/failure', :to => 'authorizations#failure'
  

  root :to => "users#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omniauth</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="logo">
      <div><%= link_to "OmniAuth demo", root_path %></div>
    </div>
    <div id="user_nav">
      <% if current_user %>
      	Welcome <%= current_user.username %> |
        <%= link_to "Edit Profile", edit_user_path(:current) %> |
        <%= link_to "Signout", logout_path %>
      <% else %>
        <%= link_to "Register", new_user_path %> |
        <%= link_to "Signin", login_path %>
      <% end %>
    </div>
    <div class="clear"></div>
    <%- flash.each do |name, msg| -%>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <%- end -%>
    
    <%- if show_title? -%>
      <h3><%=h yield(:title) %></h3>
    <%- end -%>
    
    <%= yield %>
  </div>
</body>
</html>